site_name: CAP
nav:
    - Home: index.md
    - <img src="https://www.countryflags.io/us/flat/16.png">User Guide:
        - Getting Started: user-guide/getting-started.md
        - API Interface: user-guide/api-interface.md
        - Configuration: user-guide/configuration.md
        - Design Principle: user-guide/design-principle.md.md
        - Implementation Mechanisms: user-guide/implementation-mechanisms.md
        - Distributed Transactions: user-guide/distributed-transactions.md
        - FAQ: user-guide/faq.md
    - <img src="https://www.countryflags.io/cn/flat/16.png">使用指南:
        - 快速开始: user-guide-cn/getting-started.md
        - API 接口: user-guide-cn/api-interface.md
        - 配置: user-guide-cn/configuration.md
        - 设计原理: user-guide-cn/design-principle.md
        - 实现: user-guide-cn/implementation-mechanisms.md
        - 分布式事务: user-guide-cn/distributed-transactions.md
        - FAQ: user-guide-cn/faq.md
    - About: about.md
theme: cinder
markdown_extensions:
  - admonition
repo_url: "https://github.com/dotnetcore/CAP"