<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
	<Nullable>enable</Nullable>
    <PackageTags>$(PackageTags);NATS</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NATS.Client.JetStream" Version="3.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DotNetCore.CAP\DotNetCore.CAP.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DotNetCore.CAP.NATS.Test" />
  </ItemGroup>

</Project>
