// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DiscoveryService.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace SkyWalking.NetworkProtocol {
  public static partial class InstanceDiscoveryService
  {
    static readonly string __ServiceName = "InstanceDiscoveryService";

    static readonly grpc::Marshaller<global::SkyWalking.NetworkProtocol.ApplicationInstance> __Marshaller_ApplicationInstance = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SkyWalking.NetworkProtocol.ApplicationInstance.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SkyWalking.NetworkProtocol.ApplicationInstanceMapping> __Marshaller_ApplicationInstanceMapping = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SkyWalking.NetworkProtocol.ApplicationInstanceMapping.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SkyWalking.NetworkProtocol.ApplicationInstanceHeartbeat> __Marshaller_ApplicationInstanceHeartbeat = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SkyWalking.NetworkProtocol.ApplicationInstanceHeartbeat.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SkyWalking.NetworkProtocol.Downstream> __Marshaller_Downstream = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SkyWalking.NetworkProtocol.Downstream.Parser.ParseFrom);

    static readonly grpc::Method<global::SkyWalking.NetworkProtocol.ApplicationInstance, global::SkyWalking.NetworkProtocol.ApplicationInstanceMapping> __Method_registerInstance = new grpc::Method<global::SkyWalking.NetworkProtocol.ApplicationInstance, global::SkyWalking.NetworkProtocol.ApplicationInstanceMapping>(
        grpc::MethodType.Unary,
        __ServiceName,
        "registerInstance",
        __Marshaller_ApplicationInstance,
        __Marshaller_ApplicationInstanceMapping);

    static readonly grpc::Method<global::SkyWalking.NetworkProtocol.ApplicationInstanceHeartbeat, global::SkyWalking.NetworkProtocol.Downstream> __Method_heartbeat = new grpc::Method<global::SkyWalking.NetworkProtocol.ApplicationInstanceHeartbeat, global::SkyWalking.NetworkProtocol.Downstream>(
        grpc::MethodType.Unary,
        __ServiceName,
        "heartbeat",
        __Marshaller_ApplicationInstanceHeartbeat,
        __Marshaller_Downstream);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::SkyWalking.NetworkProtocol.DiscoveryServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of InstanceDiscoveryService</summary>
    public abstract partial class InstanceDiscoveryServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::SkyWalking.NetworkProtocol.ApplicationInstanceMapping> registerInstance(global::SkyWalking.NetworkProtocol.ApplicationInstance request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SkyWalking.NetworkProtocol.Downstream> heartbeat(global::SkyWalking.NetworkProtocol.ApplicationInstanceHeartbeat request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for InstanceDiscoveryService</summary>
    public partial class InstanceDiscoveryServiceClient : grpc::ClientBase<InstanceDiscoveryServiceClient>
    {
      /// <summary>Creates a new client for InstanceDiscoveryService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public InstanceDiscoveryServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for InstanceDiscoveryService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public InstanceDiscoveryServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected InstanceDiscoveryServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected InstanceDiscoveryServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::SkyWalking.NetworkProtocol.ApplicationInstanceMapping registerInstance(global::SkyWalking.NetworkProtocol.ApplicationInstance request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return registerInstance(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SkyWalking.NetworkProtocol.ApplicationInstanceMapping registerInstance(global::SkyWalking.NetworkProtocol.ApplicationInstance request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_registerInstance, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SkyWalking.NetworkProtocol.ApplicationInstanceMapping> registerInstanceAsync(global::SkyWalking.NetworkProtocol.ApplicationInstance request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return registerInstanceAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SkyWalking.NetworkProtocol.ApplicationInstanceMapping> registerInstanceAsync(global::SkyWalking.NetworkProtocol.ApplicationInstance request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_registerInstance, null, options, request);
      }
      public virtual global::SkyWalking.NetworkProtocol.Downstream heartbeat(global::SkyWalking.NetworkProtocol.ApplicationInstanceHeartbeat request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return heartbeat(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SkyWalking.NetworkProtocol.Downstream heartbeat(global::SkyWalking.NetworkProtocol.ApplicationInstanceHeartbeat request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_heartbeat, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SkyWalking.NetworkProtocol.Downstream> heartbeatAsync(global::SkyWalking.NetworkProtocol.ApplicationInstanceHeartbeat request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return heartbeatAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SkyWalking.NetworkProtocol.Downstream> heartbeatAsync(global::SkyWalking.NetworkProtocol.ApplicationInstanceHeartbeat request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_heartbeat, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override InstanceDiscoveryServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new InstanceDiscoveryServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(InstanceDiscoveryServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_registerInstance, serviceImpl.registerInstance)
          .AddMethod(__Method_heartbeat, serviceImpl.heartbeat).Build();
    }

  }
  /// <summary>
  ///discovery service for ServiceName by Network address or application code
  /// </summary>
  public static partial class ServiceNameDiscoveryService
  {
    static readonly string __ServiceName = "ServiceNameDiscoveryService";

    static readonly grpc::Marshaller<global::SkyWalking.NetworkProtocol.ServiceNameCollection> __Marshaller_ServiceNameCollection = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SkyWalking.NetworkProtocol.ServiceNameCollection.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SkyWalking.NetworkProtocol.ServiceNameMappingCollection> __Marshaller_ServiceNameMappingCollection = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SkyWalking.NetworkProtocol.ServiceNameMappingCollection.Parser.ParseFrom);

    static readonly grpc::Method<global::SkyWalking.NetworkProtocol.ServiceNameCollection, global::SkyWalking.NetworkProtocol.ServiceNameMappingCollection> __Method_discovery = new grpc::Method<global::SkyWalking.NetworkProtocol.ServiceNameCollection, global::SkyWalking.NetworkProtocol.ServiceNameMappingCollection>(
        grpc::MethodType.Unary,
        __ServiceName,
        "discovery",
        __Marshaller_ServiceNameCollection,
        __Marshaller_ServiceNameMappingCollection);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::SkyWalking.NetworkProtocol.DiscoveryServiceReflection.Descriptor.Services[1]; }
    }

    /// <summary>Base class for server-side implementations of ServiceNameDiscoveryService</summary>
    public abstract partial class ServiceNameDiscoveryServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::SkyWalking.NetworkProtocol.ServiceNameMappingCollection> discovery(global::SkyWalking.NetworkProtocol.ServiceNameCollection request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ServiceNameDiscoveryService</summary>
    public partial class ServiceNameDiscoveryServiceClient : grpc::ClientBase<ServiceNameDiscoveryServiceClient>
    {
      /// <summary>Creates a new client for ServiceNameDiscoveryService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ServiceNameDiscoveryServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ServiceNameDiscoveryService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ServiceNameDiscoveryServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ServiceNameDiscoveryServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ServiceNameDiscoveryServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::SkyWalking.NetworkProtocol.ServiceNameMappingCollection discovery(global::SkyWalking.NetworkProtocol.ServiceNameCollection request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return discovery(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SkyWalking.NetworkProtocol.ServiceNameMappingCollection discovery(global::SkyWalking.NetworkProtocol.ServiceNameCollection request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_discovery, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SkyWalking.NetworkProtocol.ServiceNameMappingCollection> discoveryAsync(global::SkyWalking.NetworkProtocol.ServiceNameCollection request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return discoveryAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SkyWalking.NetworkProtocol.ServiceNameMappingCollection> discoveryAsync(global::SkyWalking.NetworkProtocol.ServiceNameCollection request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_discovery, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ServiceNameDiscoveryServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ServiceNameDiscoveryServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ServiceNameDiscoveryServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_discovery, serviceImpl.discovery).Build();
    }

  }
}
#endregion
