// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: NetworkAddressRegisterService.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace SkyWalking.NetworkProtocol {
  public static partial class NetworkAddressRegisterService
  {
    static readonly string __ServiceName = "NetworkAddressRegisterService";

    static readonly grpc::Marshaller<global::SkyWalking.NetworkProtocol.NetworkAddresses> __Marshaller_NetworkAddresses = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SkyWalking.NetworkProtocol.NetworkAddresses.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SkyWalking.NetworkProtocol.NetworkAddressMappings> __Marshaller_NetworkAddressMappings = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SkyWalking.NetworkProtocol.NetworkAddressMappings.Parser.ParseFrom);

    static readonly grpc::Method<global::SkyWalking.NetworkProtocol.NetworkAddresses, global::SkyWalking.NetworkProtocol.NetworkAddressMappings> __Method_batchRegister = new grpc::Method<global::SkyWalking.NetworkProtocol.NetworkAddresses, global::SkyWalking.NetworkProtocol.NetworkAddressMappings>(
        grpc::MethodType.Unary,
        __ServiceName,
        "batchRegister",
        __Marshaller_NetworkAddresses,
        __Marshaller_NetworkAddressMappings);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::SkyWalking.NetworkProtocol.NetworkAddressRegisterServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of NetworkAddressRegisterService</summary>
    public abstract partial class NetworkAddressRegisterServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::SkyWalking.NetworkProtocol.NetworkAddressMappings> batchRegister(global::SkyWalking.NetworkProtocol.NetworkAddresses request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for NetworkAddressRegisterService</summary>
    public partial class NetworkAddressRegisterServiceClient : grpc::ClientBase<NetworkAddressRegisterServiceClient>
    {
      /// <summary>Creates a new client for NetworkAddressRegisterService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public NetworkAddressRegisterServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for NetworkAddressRegisterService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public NetworkAddressRegisterServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected NetworkAddressRegisterServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected NetworkAddressRegisterServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::SkyWalking.NetworkProtocol.NetworkAddressMappings batchRegister(global::SkyWalking.NetworkProtocol.NetworkAddresses request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return batchRegister(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SkyWalking.NetworkProtocol.NetworkAddressMappings batchRegister(global::SkyWalking.NetworkProtocol.NetworkAddresses request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_batchRegister, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SkyWalking.NetworkProtocol.NetworkAddressMappings> batchRegisterAsync(global::SkyWalking.NetworkProtocol.NetworkAddresses request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return batchRegisterAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SkyWalking.NetworkProtocol.NetworkAddressMappings> batchRegisterAsync(global::SkyWalking.NetworkProtocol.NetworkAddresses request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_batchRegister, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override NetworkAddressRegisterServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new NetworkAddressRegisterServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(NetworkAddressRegisterServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_batchRegister, serviceImpl.batchRegister).Build();
    }

  }
}
#endregion
