#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetCore.CAP.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Dashboard\Pages\NodePage.cshtml"
    using DotNetCore.CAP.Dashboard;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Dashboard\Pages\NodePage.cshtml"
    using DotNetCore.CAP.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Dashboard\Pages\NodePage.cshtml"
    using DotNetCore.CAP.Dashboard.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class NodePage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");






            
            #line 6 "..\..\Dashboard\Pages\NodePage.cshtml"
  
    Layout = new LayoutPage(Strings.NodePage_Title);
    //if (CurrentNodeId != null)
    //{
    //    Session.Set("cap_current_node",System.Text.Encoding.Default.GetBytes(CurrentNodeId));
    //}


            
            #line default
            #line hidden
WriteLiteral("<div class=\"row\">\r\n    <div class=\"col-md-12\">\r\n        <h1 class=\"page-header\">");


            
            #line 15 "..\..\Dashboard\Pages\NodePage.cshtml"
                           Write(Strings.NodePage_Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n\r\n");


            
            #line 17 "..\..\Dashboard\Pages\NodePage.cshtml"
         if (Nodes == null || Nodes.Count == 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"alert alert-warning\">\r\n                ");


            
            #line 20 "..\..\Dashboard\Pages\NodePage.cshtml"
           Write(Strings.NodePage_NoNodes);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");


            
            #line 22 "..\..\Dashboard\Pages\NodePage.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral(@"            <div class=""table-responsive"">
                <table class=""table"">
                    <thead>
                        <tr>
                            <th width=""10%"">编号</th>
                            <th width=""20%"">节点名称</th>
                            <th width=""20%"">IP地址</th>
                            <th width=""7%"">端口号</th>
                            <th>Tags</th>
                            <th width=""20%"">操作</th>
                        </tr>
                    </thead>
                    <tbody>
");


            
            #line 38 "..\..\Dashboard\Pages\NodePage.cshtml"
                         foreach (var node in Nodes)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <tr class=\"");


            
            #line 40 "..\..\Dashboard\Pages\NodePage.cshtml"
                                   Write(CurrentNodeId == node.Id? "active":null );

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                <td>");


            
            #line 41 "..\..\Dashboard\Pages\NodePage.cshtml"
                               Write(node.Id);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td>");


            
            #line 42 "..\..\Dashboard\Pages\NodePage.cshtml"
                               Write(node.Name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td>");


            
            #line 43 "..\..\Dashboard\Pages\NodePage.cshtml"
                               Write(node.Address);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td>");


            
            #line 44 "..\..\Dashboard\Pages\NodePage.cshtml"
                               Write(node.Port);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td>");


            
            #line 45 "..\..\Dashboard\Pages\NodePage.cshtml"
                               Write(node.Tags);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td>\r\n                                    " +
"");


            
            #line 47 "..\..\Dashboard\Pages\NodePage.cshtml"
                               Write(Html.NodeSwitchLink(node.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n                            </tr>\r\n");


            
            #line 50 "..\..\Dashboard\Pages\NodePage.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </tbody>\r\n                </table>\r\n            </div>\r\n");


            
            #line 54 "..\..\Dashboard\Pages\NodePage.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
