#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetCore.CAP.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Dashboard\Pages\NodePage.cshtml"
    using DotNetCore.CAP.Dashboard;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Dashboard\Pages\NodePage.cshtml"
    using DotNetCore.CAP.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Dashboard\Pages\NodePage.cshtml"
    using DotNetCore.CAP.Dashboard.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class NodePage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");






            
            #line 6 "..\..\Dashboard\Pages\NodePage.cshtml"
  
    Layout = new LayoutPage(Strings.NodePage_Title);


            
            #line default
            #line hidden
WriteLiteral("<div class=\"row\">\r\n    <div class=\"col-md-12\">\r\n        <h1 class=\"page-header\">");


            
            #line 11 "..\..\Dashboard\Pages\NodePage.cshtml"
                           Write(Strings.NodePage_Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n\r\n");


            
            #line 13 "..\..\Dashboard\Pages\NodePage.cshtml"
         if (Nodes == null || Nodes.Count==0)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"alert alert-warning\">\r\n                ");


            
            #line 16 "..\..\Dashboard\Pages\NodePage.cshtml"
           Write(Strings.NodePage_NoNodes);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");


            
            #line 18 "..\..\Dashboard\Pages\NodePage.cshtml"
        }
        else
        { 

            
            #line default
            #line hidden
WriteLiteral(@"            <div class=""table-responsive"">
                <table class=""table"">
                    <thead>
                        <tr>
                            <th width=""50%"">节点名称</th>
                            <th width=""50%"">IP地址</th>
                        </tr>
                    </thead>
                    <tbody>
");


            
            #line 30 "..\..\Dashboard\Pages\NodePage.cshtml"
                         foreach (var node in Nodes)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <tr>\r\n                                <td>");


            
            #line 33 "..\..\Dashboard\Pages\NodePage.cshtml"
                               Write(node.Name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td>");


            
            #line 34 "..\..\Dashboard\Pages\NodePage.cshtml"
                               Write(node.Address);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                            </tr>\r\n");


            
            #line 36 "..\..\Dashboard\Pages\NodePage.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </tbody>\r\n                </table>\r\n            </div>\r\n");


            
            #line 40 "..\..\Dashboard\Pages\NodePage.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
