#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetCore.CAP.Dashboard.Pages
{
    
    #line 2 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
    using System;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 4 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
    using DotNetCore.CAP.Dashboard;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
    using DotNetCore.CAP.Dashboard.Monitoring;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
    using DotNetCore.CAP.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
    using DotNetCore.CAP.Dashboard.Resources;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
    using DotNetCore.CAP.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class ReceivedPage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");









            
            #line 9 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
  
    Layout = new LayoutPage(Strings.ReceivedMessagesPage_Title);

    int from, perPage;

    int.TryParse(Query("from"), out from);
    int.TryParse(Query("count"), out perPage);
    string group = Query("group");
    string name = Query("name");
    string content = Query("content");

    var monitor = Storage.GetMonitoringApi();
    var pager = new Pager(from, perPage, GetTotal(monitor));
    var queryDto = new MessageQueryDto
    {
        MessageType = MessageType.Subscribe,
        Group =group,
        Name = name,
        Content = content,
        StatusName = StatusName,
        CurrentPage = pager.CurrentPage - 1,
        PageSize = pager.RecordsPerPage
    };
    var succeededMessages = monitor.Messages(queryDto);


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"row\">\r\n    <div class=\"col-md-3\">\r\n        ");


            
            #line 37 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
   Write(Html.MessagesSidebar(MessageType.Subscribe));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div class=\"col-md-9\">\r\n        <h1 class=\"page-header\">");


            
            #line 40 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
                           Write(Strings.ReceivedPage_Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n\r\n");


            
            #line 42 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
         if (succeededMessages.Count == 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"alert alert-info\">\r\n                ");


            
            #line 45 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
           Write(Strings.MessagesPage_NoMessages);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");


            
            #line 47 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral(@"            <div class=""js-jobs-list"">
                <div class=""btn-toolbar btn-toolbar-top"">
                    <form class=""row"">
                        <span class=""col-md-2"">
                            <input type=""text"" class=""form-control"" name=""name"" value=""");


            
            #line 54 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
                                                                                  Write(Query("group"));

            
            #line default
            #line hidden
WriteLiteral("\" placeholder=\"");


            
            #line 54 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
                                                                                                                Write(Strings.MessagesPage_Query_MessageGroup);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n                        </span>\r\n                        <span class=\"col-m" +
"d-3\">\r\n                            <input type=\"text\" class=\"form-control\" name=" +
"\"name\" value=\"");


            
            #line 57 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
                                                                                  Write(Query("name"));

            
            #line default
            #line hidden
WriteLiteral("\" placeholder=\"");


            
            #line 57 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
                                                                                                               Write(Strings.MessagesPage_Query_MessageName);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n                        </span>\r\n                        <div class=\"col-md" +
"-5\">\r\n                            <div class=\"input-group\">\r\n                   " +
"             <input type=\"text\" class=\"form-control\" name=\"content\" value=\"");


            
            #line 61 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
                                                                                         Write(Query("content"));

            
            #line default
            #line hidden
WriteLiteral("\" placeholder=\"");


            
            #line 61 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
                                                                                                                         Write(Strings.MessagesPage_Query_MessageBody);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n                                <span class=\"input-group-btn\">\r\n           " +
"                         <button class=\"btn btn-info\">");


            
            #line 63 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
                                                            Write(Strings.MessagesPage_Query_Button);

            
            #line default
            #line hidden
WriteLiteral(@"</button>
                                </span>
                            </div>
                        </div>
                    </form>
                </div>
                <div class=""btn-toolbar btn-toolbar-top"">
                    <button class=""js-jobs-list-command btn btn-sm btn-primary""
                            data-url=""");


            
            #line 71 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
                                 Write(Url.To("/received/requeue"));

            
            #line default
            #line hidden
WriteLiteral("\"\r\n                            data-loading-text=\"");


            
            #line 72 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
                                          Write(Strings.Common_Enqueueing);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n                            disabled=\"disabled\">\r\n                        <spa" +
"n class=\"glyphicon glyphicon-repeat\"></span>\r\n                        ");


            
            #line 75 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
                   Write(Strings.Common_RequeueJobs);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </button>\r\n\r\n                    ");


            
            #line 78 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
               Write(Html.PerPageSelector(pager));

            
            #line default
            #line hidden
WriteLiteral(@"
                </div>

                <div class=""table-responsive"">
                    <table class=""table"">
                        <thead>
                            <tr>
                                <th style=""width:60px;"">
                                    <input type=""checkbox"" class=""js-jobs-list-select-all"" />
                                </th>
                                <th>");


            
            #line 88 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
                               Write(Strings.MessagesPage_Table_Code);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                <th>");


            
            #line 89 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
                               Write(Strings.MessagesPage_Table_Group);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                <th>");


            
            #line 90 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
                               Write(Strings.MessagesPage_Table_Name);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                <th class=\"min-width\">");


            
            #line 91 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
                                                 Write(Strings.MessagesPage_Table_Retries);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                <th class=\"align-right\">");


            
            #line 92 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
                                                   Write(Strings.MessagesPage_Table_ExpiresAt);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                            </tr>\r\n                        </thead>\r\n     " +
"                   <tbody>\r\n");


            
            #line 96 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
                             foreach (var message in succeededMessages)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <tr class=\"js-jobs-list-row hover\">\r\n            " +
"                        <td>\r\n                                        <input typ" +
"e=\"checkbox\" class=\"js-jobs-list-checkbox\" name=\"messages[]\" value=\"");


            
            #line 100 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
                                                                                                                 Write(message.Id);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n                                    </td>\r\n                                " +
"    <td class=\"word-break\">\r\n                                        <a href=\"ja" +
"vascript:;\" data-url=\'");


            
            #line 103 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
                                                                     Write(Url.To("/received/message/")+message.Id);

            
            #line default
            #line hidden
WriteLiteral("\' class=\"openModal\">#");


            
            #line 103 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
                                                                                                                                   Write(message.Id);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                                    </td>\r\n                                " +
"    <td>\r\n                                        ");


            
            #line 106 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
                                   Write(message.Group);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n                                    " +
"<td>\r\n                                        ");


            
            #line 109 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
                                   Write(message.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n                                    " +
"<td>\r\n                                        ");


            
            #line 112 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
                                   Write(message.Retries);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n                                    " +
"<td class=\"align-right\">\r\n");


            
            #line 115 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
                                         if (message.ExpiresAt.HasValue)
                                        {
                                            
            
            #line default
            #line hidden
            
            #line 117 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
                                       Write(Html.RelativeTime(message.ExpiresAt.Value));

            
            #line default
            #line hidden
            
            #line 117 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
                                                                                       
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </td>\r\n\r\n                                </tr" +
">\r\n");


            
            #line 122 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </tbody>\r\n                    </table>\r\n                <" +
"/div>\r\n                ");


            
            #line 126 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
           Write(Html.Paginator(pager));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");


            
            #line 128 "..\..\Dashboard\Pages\ReceivedPage.cshtml"


            
            #line default
            #line hidden
WriteLiteral(@"            <div>
                <div class=""modal fade"" tabindex=""-1"" role=""dialog"">
                    <div class=""modal-dialog"" role=""document"">
                        <div class=""modal-content"">
                            <div class=""modal-header"">
                                <button type=""button"" class=""close"" data-dismiss=""modal"" aria-label=""Close""><span aria-hidden=""true"">&times;</span></button>
                                <h4 class=""modal-title"">Message Content</h4>
                            </div>
                            <div id=""jsonContent"" style=""max-height:500px;overflow-y:auto;"" class=""modal-body"">
                            </div>
                            <div class=""modal-footer"">
                                <button type=""button"" class=""btn btn-sm btn-primary"" id=""formatBtn"" onclick="""">");


            
            #line 140 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
                                                                                                          Write(Strings.MessagesPage_Modal_Format);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                                <button type=\"button\" class=\"btn btn-s" +
"m btn-primary\" id=\"rawBtn\" onclick=\"\">");


            
            #line 141 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
                                                                                                       Write(Strings.MessagesPage_Modal_Raw);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                                <button type=\"button\" class=\"btn btn-s" +
"m btn-primary\" id=\"expandBtn\" onclick=\"\">");


            
            #line 142 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
                                                                                                          Write(Strings.MessagesPage_Modal_Expand);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                                <button type=\"button\" class=\"btn btn-s" +
"m btn-primary\" id=\"collapseBtn\" onclick=\"\">");


            
            #line 143 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
                                                                                                            Write(Strings.MessagesPage_Model_Collaspse);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                            </div>\r\n                        </div><!--" +
" /.modal-content -->\r\n                    </div><!-- /.modal-dialog -->\r\n       " +
"         </div><!-- /.modal -->\r\n            </div>\r\n");


            
            #line 149 "..\..\Dashboard\Pages\ReceivedPage.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
