#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetCore.CAP.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 3 "..\..\Dashboard\Pages\SubscriberPage.cshtml"
    using DotNetCore.CAP.Dashboard;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Dashboard\Pages\SubscriberPage.cshtml"
    using DotNetCore.CAP.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Dashboard\Pages\SubscriberPage.cshtml"
    using DotNetCore.CAP.Dashboard.Resources;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Dashboard\Pages\SubscriberPage.cshtml"
    using DotNetCore.CAP.Internal;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class SubscriberPage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");







            
            #line 7 "..\..\Dashboard\Pages\SubscriberPage.cshtml"
  
    Layout = new LayoutPage(Strings.SubscribersPage_Title);

    var cache = RequestServices.GetService(typeof(MethodMatcherCache)) as MethodMatcherCache;
    var subscribers = cache.GetCandidatesMethodsOfGroupNameGrouped();


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"row\">\r\n    <div class=\"col-md-12\">\r\n        <h1 class=\"page-header\"" +
">");


            
            #line 16 "..\..\Dashboard\Pages\SubscriberPage.cshtml"
                           Write(Strings.SubscribersPage_Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n\r\n");


            
            #line 18 "..\..\Dashboard\Pages\SubscriberPage.cshtml"
         if (subscribers.Count == 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"alert alert-warning\">\r\n\r\n                ");


            
            #line 22 "..\..\Dashboard\Pages\SubscriberPage.cshtml"
           Write(Strings.ServersPage_NoServers);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");


            
            #line 24 "..\..\Dashboard\Pages\SubscriberPage.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"table-responsive\">\r\n                <table class=\"table\">" +
"\r\n                    <thead>\r\n                        <tr>\r\n                   " +
"         <th width=\"20%\">");


            
            #line 31 "..\..\Dashboard\Pages\SubscriberPage.cshtml"
                                       Write(Strings.Common_Group);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                            <th>\r\n                                <table c" +
"lass=\"table subscribe-table margin-bottom-zero\"><tr><td width=\"40%\">");


            
            #line 33 "..\..\Dashboard\Pages\SubscriberPage.cshtml"
                                                                                                       Write(Strings.Common_Name);

            
            #line default
            #line hidden
WriteLiteral("</td><td>");


            
            #line 33 "..\..\Dashboard\Pages\SubscriberPage.cshtml"
                                                                                                                                    Write(Strings.Common_Method);

            
            #line default
            #line hidden
WriteLiteral("</td></tr></table>\r\n                            </th>\r\n                        </" +
"tr>\r\n                    </thead>\r\n                    <tbody>\r\n");


            
            #line 38 "..\..\Dashboard\Pages\SubscriberPage.cshtml"
                         foreach (var subscriber in subscribers)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <tr>\r\n                                <td style=\"vert" +
"ical-align:middle;font-weight:bold;\">");


            
            #line 41 "..\..\Dashboard\Pages\SubscriberPage.cshtml"
                                                                               Write(subscriber.Key);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td>\r\n                                    " +
"<table class=\"table subscribe-table table-condensed margin-bottom-zero\">\r\n");


            
            #line 44 "..\..\Dashboard\Pages\SubscriberPage.cshtml"
                                         foreach (var column in subscriber.Value)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <tr>\r\n                               " +
"                 <td width=\"40%\">");


            
            #line 47 "..\..\Dashboard\Pages\SubscriberPage.cshtml"
                                                           Write(column.Attribute.Name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                                <td><span style=\"color:#00" +
"bcd4\">");


            
            #line 48 "..\..\Dashboard\Pages\SubscriberPage.cshtml"
                                                                           Write(column.ImplTypeInfo.Name);

            
            #line default
            #line hidden
WriteLiteral("</span>： \r\n                                                 ");


            
            #line 49 "..\..\Dashboard\Pages\SubscriberPage.cshtml"
                                            Write(Html.MethodEscaped(column.MethodInfo));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                </td>\r\n                        " +
"                    </tr>\r\n");


            
            #line 52 "..\..\Dashboard\Pages\SubscriberPage.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </table>\r\n                                </t" +
"d>\r\n                            </tr>\r\n");


            
            #line 56 "..\..\Dashboard\Pages\SubscriberPage.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </tbody>\r\n                </table>\r\n            </div>\r\n");


            
            #line 60 "..\..\Dashboard\Pages\SubscriberPage.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
