// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Common.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SkyWalking.NetworkProtocol {

  /// <summary>Holder for reflection information generated from Common.proto</summary>
  public static partial class CommonReflection {

    #region Descriptor
    /// <summary>File descriptor for Common.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxDb21tb24ucHJvdG8qKgoIU3BhblR5cGUSCQoFRW50cnkQABIICgRFeGl0",
            "EAESCQoFTG9jYWwQAkJICidvcmcuYXBhY2hlLnNreXdhbGtpbmcuYXBtLm5l",
            "dHdvcmsucHJvdG9QAaoCGlNreVdhbGtpbmcuTmV0d29ya1Byb3RvY29sYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::SkyWalking.NetworkProtocol.SpanType), }, null));
    }
    #endregion

  }
  #region Enums
  public enum SpanType {
    [pbr::OriginalName("Entry")] Entry = 0,
    [pbr::OriginalName("Exit")] Exit = 1,
    [pbr::OriginalName("Local")] Local = 2,
  }

  #endregion

}

#endregion Designer generated code
