//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetCore.CAP.Dashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetCore.CAP.Dashboard.Content.resx.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find the target method..
        /// </summary>
        public static string Common_CannotFindTargetMethod {
            get {
                return ResourceManager.GetString("Common_CannotFindTargetMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        public static string Common_Condition {
            get {
                return ResourceManager.GetString("Common_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuations.
        /// </summary>
        public static string Common_Continuations {
            get {
                return ResourceManager.GetString("Common_Continuations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Common_Created {
            get {
                return ResourceManager.GetString("Common_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to DELETE ALL selected jobs?.
        /// </summary>
        public static string Common_DeleteConfirm {
            get {
                return ResourceManager.GetString("Common_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected.
        /// </summary>
        public static string Common_DeleteSelected {
            get {
                return ResourceManager.GetString("Common_DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting....
        /// </summary>
        public static string Common_Deleting {
            get {
                return ResourceManager.GetString("Common_Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueue jobs.
        /// </summary>
        public static string Common_EnqueueButton_Text {
            get {
                return ResourceManager.GetString("Common_EnqueueButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueued.
        /// </summary>
        public static string Common_Enqueued {
            get {
                return ResourceManager.GetString("Common_Enqueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueueing....
        /// </summary>
        public static string Common_Enqueueing {
            get {
                return ResourceManager.GetString("Common_Enqueueing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetched.
        /// </summary>
        public static string Common_Fetched {
            get {
                return ResourceManager.GetString("Common_Fetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Common_Id {
            get {
                return ResourceManager.GetString("Common_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string Common_Job {
            get {
                return ResourceManager.GetString("Common_Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job expired..
        /// </summary>
        public static string Common_JobExpired {
            get {
                return ResourceManager.GetString("Common_JobExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job&apos;s state has been changed while fetching data..
        /// </summary>
        public static string Common_JobStateChanged_Text {
            get {
                return ResourceManager.GetString("Common_JobStateChanged_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less details....
        /// </summary>
        public static string Common_LessDetails {
            get {
                return ResourceManager.GetString("Common_LessDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More details....
        /// </summary>
        public static string Common_MoreDetails {
            get {
                return ResourceManager.GetString("Common_MoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No state.
        /// </summary>
        public static string Common_NoState {
            get {
                return ResourceManager.GetString("Common_NoState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string Common_NotAvailable {
            get {
                return ResourceManager.GetString("Common_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Common_PeriodDay {
            get {
                return ResourceManager.GetString("Common_PeriodDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string Common_PeriodWeek {
            get {
                return ResourceManager.GetString("Common_PeriodWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string Common_Reason {
            get {
                return ResourceManager.GetString("Common_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requeue jobs.
        /// </summary>
        public static string Common_RequeueJobs {
            get {
                return ResourceManager.GetString("Common_RequeueJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Common_Retry {
            get {
                return ResourceManager.GetString("Common_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string Common_Server {
            get {
                return ResourceManager.GetString("Common_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string Common_State {
            get {
                return ResourceManager.GetString("Common_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Common_Unknown {
            get {
                return ResourceManager.GetString("Common_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The queue is empty..
        /// </summary>
        public static string EnqueuedJobsPage_NoJobs {
            get {
                return ResourceManager.GetString("EnqueuedJobsPage_NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueued jobs.
        /// </summary>
        public static string EnqueuedJobsPage_Title {
            get {
                return ResourceManager.GetString("EnqueuedJobsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Failed jobs do not become expired&lt;/strong&gt; to allow you to re-queue them without any
        ///                time pressure. You should re-queue or delete them manually, or apply &lt;code&gt;AutomaticRetry(OnAttemptsExceeded = AttemptsExceededAction.Delete)&lt;/code&gt;
        ///                attribute to delete them automatically..
        /// </summary>
        public static string FailedJobsPage_FailedJobsNotExpire_Warning_Html {
            get {
                return ResourceManager.GetString("FailedJobsPage_FailedJobsNotExpire_Warning_Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no failed jobs at the moment..
        /// </summary>
        public static string FailedJobsPage_NoJobs {
            get {
                return ResourceManager.GetString("FailedJobsPage_NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string FailedJobsPage_Table_Failed {
            get {
                return ResourceManager.GetString("FailedJobsPage_Table_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Jobs.
        /// </summary>
        public static string FailedJobsPage_Title {
            get {
                return ResourceManager.GetString("FailedJobsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The queue is empty..
        /// </summary>
        public static string FetchedJobsPage_NoJobs {
            get {
                return ResourceManager.GetString("FetchedJobsPage_NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetched jobs.
        /// </summary>
        public static string FetchedJobsPage_Title {
            get {
                return ResourceManager.GetString("FetchedJobsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string HomePage_GraphHover_Failed {
            get {
                return ResourceManager.GetString("HomePage_GraphHover_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeeded.
        /// </summary>
        public static string HomePage_GraphHover_Succeeded {
            get {
                return ResourceManager.GetString("HomePage_GraphHover_Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History graph.
        /// </summary>
        public static string HomePage_HistoryGraph {
            get {
                return ResourceManager.GetString("HomePage_HistoryGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realtime graph.
        /// </summary>
        public static string HomePage_RealtimeGraph {
            get {
                return ResourceManager.GetString("HomePage_RealtimeGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string HomePage_Title {
            get {
                return ResourceManager.GetString("HomePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to site.
        /// </summary>
        public static string LayoutPage_Back {
            get {
                return ResourceManager.GetString("LayoutPage_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated: {0}ms.
        /// </summary>
        public static string LayoutPage_Footer_Generatedms {
            get {
                return ResourceManager.GetString("LayoutPage_Footer_Generatedms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        public static string LayoutPage_Footer_Time {
            get {
                return ResourceManager.GetString("LayoutPage_Footer_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        public static string MessagesPage_Modal_Expand {
            get {
                return ResourceManager.GetString("MessagesPage_Modal_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string MessagesPage_Modal_Format {
            get {
                return ResourceManager.GetString("MessagesPage_Modal_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw.
        /// </summary>
        public static string MessagesPage_Modal_Raw {
            get {
                return ResourceManager.GetString("MessagesPage_Modal_Raw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collaspse.
        /// </summary>
        public static string MessagesPage_Model_Collaspse {
            get {
                return ResourceManager.GetString("MessagesPage_Model_Collaspse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No published messages found..
        /// </summary>
        public static string MessagesPage_NoMessages {
            get {
                return ResourceManager.GetString("MessagesPage_NoMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        public static string MessagesPage_Query_Button {
            get {
                return ResourceManager.GetString("MessagesPage_Query_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message body.
        /// </summary>
        public static string MessagesPage_Query_MessageBody {
            get {
                return ResourceManager.GetString("MessagesPage_Query_MessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message group.
        /// </summary>
        public static string MessagesPage_Query_MessageGroup {
            get {
                return ResourceManager.GetString("MessagesPage_Query_MessageGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message name.
        /// </summary>
        public static string MessagesPage_Query_MessageName {
            get {
                return ResourceManager.GetString("MessagesPage_Query_MessageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string MessagesPage_Table_Code {
            get {
                return ResourceManager.GetString("MessagesPage_Table_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expries At.
        /// </summary>
        public static string MessagesPage_Table_ExpiresAt {
            get {
                return ResourceManager.GetString("MessagesPage_Table_ExpiresAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string MessagesPage_Table_Group {
            get {
                return ResourceManager.GetString("MessagesPage_Table_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string MessagesPage_Table_Name {
            get {
                return ResourceManager.GetString("MessagesPage_Table_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retries.
        /// </summary>
        public static string MessagesPage_Table_Retries {
            get {
                return ResourceManager.GetString("MessagesPage_Table_Retries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Connections.
        /// </summary>
        public static string Metrics_ActiveConnections {
            get {
                return ResourceManager.GetString("Metrics_ActiveConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting.
        /// </summary>
        public static string Metrics_AwaitingCount {
            get {
                return ResourceManager.GetString("Metrics_AwaitingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Jobs.
        /// </summary>
        public static string Metrics_DeletedJobs {
            get {
                return ResourceManager.GetString("Metrics_DeletedJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueued.
        /// </summary>
        public static string Metrics_EnqueuedCountOrNull {
            get {
                return ResourceManager.GetString("Metrics_EnqueuedCountOrNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueued / Queues.
        /// </summary>
        public static string Metrics_EnqueuedQueuesCount {
            get {
                return ResourceManager.GetString("Metrics_EnqueuedQueuesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} failed job(s) found. Retry or delete them manually..
        /// </summary>
        public static string Metrics_FailedCountOrNull {
            get {
                return ResourceManager.GetString("Metrics_FailedCountOrNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Jobs.
        /// </summary>
        public static string Metrics_FailedJobs {
            get {
                return ResourceManager.GetString("Metrics_FailedJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Jobs.
        /// </summary>
        public static string Metrics_ProcessingJobs {
            get {
                return ResourceManager.GetString("Metrics_ProcessingJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring Jobs.
        /// </summary>
        public static string Metrics_RecurringJobs {
            get {
                return ResourceManager.GetString("Metrics_RecurringJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retries.
        /// </summary>
        public static string Metrics_Retries {
            get {
                return ResourceManager.GetString("Metrics_Retries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Jobs.
        /// </summary>
        public static string Metrics_ScheduledJobs {
            get {
                return ResourceManager.GetString("Metrics_ScheduledJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers.
        /// </summary>
        public static string Metrics_Servers {
            get {
                return ResourceManager.GetString("Metrics_Servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeeded Jobs.
        /// </summary>
        public static string Metrics_SucceededJobs {
            get {
                return ResourceManager.GetString("Metrics_SucceededJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Connections.
        /// </summary>
        public static string Metrics_TotalConnections {
            get {
                return ResourceManager.GetString("Metrics_TotalConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string NavigationMenu_Published {
            get {
                return ResourceManager.GetString("NavigationMenu_Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        public static string NavigationMenu_Received {
            get {
                return ResourceManager.GetString("NavigationMenu_Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers.
        /// </summary>
        public static string NavigationMenu_Servers {
            get {
                return ResourceManager.GetString("NavigationMenu_Servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribers.
        /// </summary>
        public static string NavigationMenu_Subscribers {
            get {
                return ResourceManager.GetString("NavigationMenu_Subscribers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Paginator_Next {
            get {
                return ResourceManager.GetString("Paginator_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string Paginator_Prev {
            get {
                return ResourceManager.GetString("Paginator_Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total items.
        /// </summary>
        public static string Paginator_TotalItems {
            get {
                return ResourceManager.GetString("Paginator_TotalItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items per page.
        /// </summary>
        public static string PerPageSelector_ItemsPerPage {
            get {
                return ResourceManager.GetString("PerPageSelector_ItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like the job was aborted.
        /// </summary>
        public static string ProcessingJobsPage_Aborted {
            get {
                return ResourceManager.GetString("ProcessingJobsPage_Aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No jobs are being processed right now..
        /// </summary>
        public static string ProcessingJobsPage_NoJobs {
            get {
                return ResourceManager.GetString("ProcessingJobsPage_NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        public static string ProcessingJobsPage_Table_Started {
            get {
                return ResourceManager.GetString("ProcessingJobsPage_Table_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Jobs.
        /// </summary>
        public static string ProcessingJobsPage_Title {
            get {
                return ResourceManager.GetString("ProcessingJobsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published Messages.
        /// </summary>
        public static string PublishedMessagesPage_Title {
            get {
                return ResourceManager.GetString("PublishedMessagesPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published Jobs.
        /// </summary>
        public static string PublishedPage_Title {
            get {
                return ResourceManager.GetString("PublishedPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Messages.
        /// </summary>
        public static string ReceivedMessagesPage_Title {
            get {
                return ResourceManager.GetString("ReceivedMessagesPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Messages.
        /// </summary>
        public static string ReceivedPage_Title {
            get {
                return ResourceManager.GetString("ReceivedPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All is OK – you have no retries..
        /// </summary>
        public static string RetriesPage_NoJobs {
            get {
                return ResourceManager.GetString("RetriesPage_NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retries.
        /// </summary>
        public static string RetriesPage_Title {
            get {
                return ResourceManager.GetString("RetriesPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Retries are working, but this page can&apos;t be displayed&lt;/h4&gt;
        ///        &lt;p&gt;
        ///            Don&apos;t worry, retries are working as expected. Your current job storage does not support
        ///            some queries required to show this page. Please try to update your storage or wait until
        ///            the full command set is implemented.
        ///        &lt;/p&gt;
        ///        &lt;p&gt;
        ///            Please go to the &lt;a href=&quot;{0}&quot;&gt;Scheduled jobs&lt;/a&gt; page to see all the
        ///            scheduled jobs including retries.
        ///        &lt;/p&gt;.
        /// </summary>
        public static string RetriesPage_Warning_Html {
            get {
                return ResourceManager.GetString("RetriesPage_Warning_Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no active servers. Background tasks will not be processed..
        /// </summary>
        public static string ServersPage_NoServers {
            get {
                return ResourceManager.GetString("ServersPage_NoServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heartbeat.
        /// </summary>
        public static string ServersPage_Table_Heartbeat {
            get {
                return ResourceManager.GetString("ServersPage_Table_Heartbeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ServersPage_Table_Name {
            get {
                return ResourceManager.GetString("ServersPage_Table_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queues.
        /// </summary>
        public static string ServersPage_Table_Queues {
            get {
                return ResourceManager.GetString("ServersPage_Table_Queues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        public static string ServersPage_Table_Started {
            get {
                return ResourceManager.GetString("ServersPage_Table_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workers.
        /// </summary>
        public static string ServersPage_Table_Workers {
            get {
                return ResourceManager.GetString("ServersPage_Table_Workers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers.
        /// </summary>
        public static string ServersPage_Title {
            get {
                return ResourceManager.GetString("ServersPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string SidebarMenu_Failed {
            get {
                return ResourceManager.GetString("SidebarMenu_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string SidebarMenu_Processing {
            get {
                return ResourceManager.GetString("SidebarMenu_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeeded.
        /// </summary>
        public static string SidebarMenu_Succeeded {
            get {
                return ResourceManager.GetString("SidebarMenu_Succeeded", resourceCulture);
            }
        }
    }
}
