//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetCore.CAP.Dashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetCore.CAP.Dashboard.Content.resx.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Common_Created {
            get {
                return ResourceManager.GetString("Common_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected.
        /// </summary>
        public static string Common_DeleteSelected {
            get {
                return ResourceManager.GetString("Common_DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting....
        /// </summary>
        public static string Common_Deleting {
            get {
                return ResourceManager.GetString("Common_Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueued.
        /// </summary>
        public static string Common_Enqueued {
            get {
                return ResourceManager.GetString("Common_Enqueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueueing....
        /// </summary>
        public static string Common_Enqueueing {
            get {
                return ResourceManager.GetString("Common_Enqueueing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetched.
        /// </summary>
        public static string Common_Fetched {
            get {
                return ResourceManager.GetString("Common_Fetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Common_Group {
            get {
                return ResourceManager.GetString("Common_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Common_Id {
            get {
                return ResourceManager.GetString("Common_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less details....
        /// </summary>
        public static string Common_LessDetails {
            get {
                return ResourceManager.GetString("Common_LessDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        public static string Common_Method {
            get {
                return ResourceManager.GetString("Common_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More details....
        /// </summary>
        public static string Common_MoreDetails {
            get {
                return ResourceManager.GetString("Common_MoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Common_Name {
            get {
                return ResourceManager.GetString("Common_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string Common_NotAvailable {
            get {
                return ResourceManager.GetString("Common_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Common_PeriodDay {
            get {
                return ResourceManager.GetString("Common_PeriodDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string Common_PeriodWeek {
            get {
                return ResourceManager.GetString("Common_PeriodWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string Common_Reason {
            get {
                return ResourceManager.GetString("Common_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReExecution.
        /// </summary>
        public static string Common_ReConsume {
            get {
                return ResourceManager.GetString("Common_ReConsume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requeue messages.
        /// </summary>
        public static string Common_RequeueMessages {
            get {
                return ResourceManager.GetString("Common_RequeueMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Common_Retry {
            get {
                return ResourceManager.GetString("Common_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string Common_Server {
            get {
                return ResourceManager.GetString("Common_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string Common_State {
            get {
                return ResourceManager.GetString("Common_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Common_Unknown {
            get {
                return ResourceManager.GetString("Common_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Common_Version {
            get {
                return ResourceManager.GetString("Common_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Failed.
        /// </summary>
        public static string HomePage_GraphHover_PFailed {
            get {
                return ResourceManager.GetString("HomePage_GraphHover_PFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Succeeded.
        /// </summary>
        public static string HomePage_GraphHover_PSucceeded {
            get {
                return ResourceManager.GetString("HomePage_GraphHover_PSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumption Failed.
        /// </summary>
        public static string HomePage_GraphHover_RFailed {
            get {
                return ResourceManager.GetString("HomePage_GraphHover_RFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumption Succeeded.
        /// </summary>
        public static string HomePage_GraphHover_RSucceeded {
            get {
                return ResourceManager.GetString("HomePage_GraphHover_RSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24h graph.
        /// </summary>
        public static string HomePage_HistoryGraph {
            get {
                return ResourceManager.GetString("HomePage_HistoryGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realtime graph.
        /// </summary>
        public static string HomePage_RealtimeGraph {
            get {
                return ResourceManager.GetString("HomePage_RealtimeGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string HomePage_Title {
            get {
                return ResourceManager.GetString("HomePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to site.
        /// </summary>
        public static string LayoutPage_Back {
            get {
                return ResourceManager.GetString("LayoutPage_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated: {0}ms.
        /// </summary>
        public static string LayoutPage_Footer_Generatedms {
            get {
                return ResourceManager.GetString("LayoutPage_Footer_Generatedms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node: {0}.
        /// </summary>
        public static string LayoutPage_Footer_NodeCurrent {
            get {
                return ResourceManager.GetString("LayoutPage_Footer_NodeCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        public static string LayoutPage_Footer_Time {
            get {
                return ResourceManager.GetString("LayoutPage_Footer_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        public static string MessagesPage_Modal_Expand {
            get {
                return ResourceManager.GetString("MessagesPage_Modal_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string MessagesPage_Modal_Format {
            get {
                return ResourceManager.GetString("MessagesPage_Modal_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw.
        /// </summary>
        public static string MessagesPage_Modal_Raw {
            get {
                return ResourceManager.GetString("MessagesPage_Modal_Raw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collaspse.
        /// </summary>
        public static string MessagesPage_Model_Collaspse {
            get {
                return ResourceManager.GetString("MessagesPage_Model_Collaspse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No messages found..
        /// </summary>
        public static string MessagesPage_NoMessages {
            get {
                return ResourceManager.GetString("MessagesPage_NoMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        public static string MessagesPage_Query_Button {
            get {
                return ResourceManager.GetString("MessagesPage_Query_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message body.
        /// </summary>
        public static string MessagesPage_Query_MessageBody {
            get {
                return ResourceManager.GetString("MessagesPage_Query_MessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message group.
        /// </summary>
        public static string MessagesPage_Query_MessageGroup {
            get {
                return ResourceManager.GetString("MessagesPage_Query_MessageGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message name.
        /// </summary>
        public static string MessagesPage_Query_MessageName {
            get {
                return ResourceManager.GetString("MessagesPage_Query_MessageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string MessagesPage_Table_Code {
            get {
                return ResourceManager.GetString("MessagesPage_Table_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expries At.
        /// </summary>
        public static string MessagesPage_Table_ExpiresAt {
            get {
                return ResourceManager.GetString("MessagesPage_Table_ExpiresAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string MessagesPage_Table_Group {
            get {
                return ResourceManager.GetString("MessagesPage_Table_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string MessagesPage_Table_Name {
            get {
                return ResourceManager.GetString("MessagesPage_Table_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retries.
        /// </summary>
        public static string MessagesPage_Table_Retries {
            get {
                return ResourceManager.GetString("MessagesPage_Table_Retries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string MessagesPage_Table_State {
            get {
                return ResourceManager.GetString("MessagesPage_Table_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueued.
        /// </summary>
        public static string Metrics_EnqueuedCountOrNull {
            get {
                return ResourceManager.GetString("Metrics_EnqueuedCountOrNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueued / Queues.
        /// </summary>
        public static string Metrics_EnqueuedQueuesCount {
            get {
                return ResourceManager.GetString("Metrics_EnqueuedQueuesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} failed message(s) found. .
        /// </summary>
        public static string Metrics_FailedCountOrNull {
            get {
                return ResourceManager.GetString("Metrics_FailedCountOrNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers.
        /// </summary>
        public static string Metrics_Servers {
            get {
                return ResourceManager.GetString("Metrics_Servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Connections.
        /// </summary>
        public static string Metrics_TotalConnections {
            get {
                return ResourceManager.GetString("Metrics_TotalConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string NavigationMenu_Published {
            get {
                return ResourceManager.GetString("NavigationMenu_Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        public static string NavigationMenu_Received {
            get {
                return ResourceManager.GetString("NavigationMenu_Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers.
        /// </summary>
        public static string NavigationMenu_Servers {
            get {
                return ResourceManager.GetString("NavigationMenu_Servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribers.
        /// </summary>
        public static string NavigationMenu_Subscribers {
            get {
                return ResourceManager.GetString("NavigationMenu_Subscribers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no config distributed node discory.
        /// </summary>
        public static string NodePage_NoNodes {
            get {
                return ResourceManager.GetString("NodePage_NoNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch.
        /// </summary>
        public static string NodePage_Switch {
            get {
                return ResourceManager.GetString("NodePage_Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string NodePage_Table_IP {
            get {
                return ResourceManager.GetString("NodePage_Table_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Name.
        /// </summary>
        public static string NodePage_Table_NodeName {
            get {
                return ResourceManager.GetString("NodePage_Table_NodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string NodePage_Table_Port {
            get {
                return ResourceManager.GetString("NodePage_Table_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodes.
        /// </summary>
        public static string NodePage_Title {
            get {
                return ResourceManager.GetString("NodePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Paginator_Next {
            get {
                return ResourceManager.GetString("Paginator_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string Paginator_Prev {
            get {
                return ResourceManager.GetString("Paginator_Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total items.
        /// </summary>
        public static string Paginator_TotalItems {
            get {
                return ResourceManager.GetString("Paginator_TotalItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items per page.
        /// </summary>
        public static string PerPageSelector_ItemsPerPage {
            get {
                return ResourceManager.GetString("PerPageSelector_ItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published Messages.
        /// </summary>
        public static string PublishedMessagesPage_Title {
            get {
                return ResourceManager.GetString("PublishedMessagesPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published messages.
        /// </summary>
        public static string PublishedPage_Title {
            get {
                return ResourceManager.GetString("PublishedPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Messages.
        /// </summary>
        public static string ReceivedMessagesPage_Title {
            get {
                return ResourceManager.GetString("ReceivedMessagesPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Messages.
        /// </summary>
        public static string ReceivedPage_Title {
            get {
                return ResourceManager.GetString("ReceivedPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string SidebarMenu_Failed {
            get {
                return ResourceManager.GetString("SidebarMenu_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeeded.
        /// </summary>
        public static string SidebarMenu_Succeeded {
            get {
                return ResourceManager.GetString("SidebarMenu_Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no config CAP subscribers..
        /// </summary>
        public static string SubscribersPage_NoSubscribers {
            get {
                return ResourceManager.GetString("SubscribersPage_NoSubscribers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribers.
        /// </summary>
        public static string SubscribersPage_Title {
            get {
                return ResourceManager.GetString("SubscribersPage_Title", resourceCulture);
            }
        }
    }
}
