#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetCore.CAP.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class Breadcrumbs : DotNetCore.CAP.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");


WriteLiteral("\r\n<ol class=\"breadcrumb\">\r\n    <li>\r\n        <a href=\"");


            
            #line 6 "..\..\Pages\_Breadcrumbs.cshtml"
            Write(Url.Home());

            
            #line default
            #line hidden
WriteLiteral("\">\r\n            <span class=\"glyphicon glyphicon-home\"></span>\r\n        </a>\r\n   " +
" </li>\r\n");


            
            #line 10 "..\..\Pages\_Breadcrumbs.cshtml"
     foreach (var item in Items)
    {

            
            #line default
            #line hidden
WriteLiteral("        <li>\r\n            <a href=\"");


            
            #line 13 "..\..\Pages\_Breadcrumbs.cshtml"
                Write(item.Value);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 13 "..\..\Pages\_Breadcrumbs.cshtml"
                             Write(item.Key);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n        </li>\r\n");


            
            #line 15 "..\..\Pages\_Breadcrumbs.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <li class=\"active\">");


            
            #line 16 "..\..\Pages\_Breadcrumbs.cshtml"
                  Write(Title);

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n</ol>");


        }
    }
}
#pragma warning restore 1591
