#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetCore.CAP.Dashboard.Pages
{
    
    #line 2 "..\..\Pages\ReceivedPage.cshtml"
    using System;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 3 "..\..\Pages\ReceivedPage.cshtml"
    using DotNetCore.CAP.Dashboard;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Pages\ReceivedPage.cshtml"
    using DotNetCore.CAP.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Pages\ReceivedPage.cshtml"
    using DotNetCore.CAP.Dashboard.Resources;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Pages\ReceivedPage.cshtml"
    using DotNetCore.CAP.Messages;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Pages\ReceivedPage.cshtml"
    using DotNetCore.CAP.Monitoring;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class ReceivedPage : DotNetCore.CAP.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");









            
            #line 9 "..\..\Pages\ReceivedPage.cshtml"
  
    Layout = new LayoutPage(Strings.ReceivedMessagesPage_Title);

    int from, perPage;

    int.TryParse(Query("from"), out from);
    int.TryParse(Query("count"), out perPage);
    var group = Query("group");
    var name = Query("name");
    var content = Query("content");

    var monitor = Storage.GetMonitoringApi();
    var pager = new Pager(from, perPage, GetTotal(monitor));
    var queryDto = new MessageQueryDto
    {
        MessageType = MessageType.Subscribe,
        Group = group,
        Name = name,
        Content = content,
        StatusName = StatusName,
        CurrentPage = pager.CurrentPage - 1,
        PageSize = pager.RecordsPerPage
    };
    var succeededMessages = monitor.Messages(queryDto);


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"row\">\r\n    <div class=\"col-md-3\">\r\n        ");


            
            #line 37 "..\..\Pages\ReceivedPage.cshtml"
   Write(Html.MessagesSidebar(MessageType.Subscribe));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div class=\"col-md-9\">\r\n        <h1 class=\"page-header\">");


            
            #line 40 "..\..\Pages\ReceivedPage.cshtml"
                           Write(Strings.ReceivedPage_Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n\r\n");


            
            #line 42 "..\..\Pages\ReceivedPage.cshtml"
         if (succeededMessages.Count == 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"alert alert-info\">\r\n                ");


            
            #line 45 "..\..\Pages\ReceivedPage.cshtml"
           Write(Strings.MessagesPage_NoMessages);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");


            
            #line 47 "..\..\Pages\ReceivedPage.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral(@"            <div class=""js-jobs-list"">
                <div class=""btn-toolbar btn-toolbar-top"">
                    <form class=""row"">
                        <div class=""col-md-2"">
                            <input type=""text"" class=""form-control"" name=""group"" value=""");


            
            #line 54 "..\..\Pages\ReceivedPage.cshtml"
                                                                                   Write(Query("group"));

            
            #line default
            #line hidden
WriteLiteral("\" placeholder=\"");


            
            #line 54 "..\..\Pages\ReceivedPage.cshtml"
                                                                                                                 Write(Strings.MessagesPage_Query_MessageGroup);

            
            #line default
            #line hidden
WriteLiteral("\"/>\r\n                        </div>\r\n                        <div class=\"col-md-3" +
"\">\r\n                            <input type=\"text\" class=\"form-control\" name=\"na" +
"me\" value=\"");


            
            #line 57 "..\..\Pages\ReceivedPage.cshtml"
                                                                                  Write(Query("name"));

            
            #line default
            #line hidden
WriteLiteral("\" placeholder=\"");


            
            #line 57 "..\..\Pages\ReceivedPage.cshtml"
                                                                                                               Write(Strings.MessagesPage_Query_MessageName);

            
            #line default
            #line hidden
WriteLiteral("\"/>\r\n                        </div>\r\n                        <div class=\"col-md-5" +
"\">\r\n                            <div class=\"input-group\">\r\n                     " +
"           <input type=\"text\" class=\"form-control\" name=\"content\" value=\"");


            
            #line 61 "..\..\Pages\ReceivedPage.cshtml"
                                                                                         Write(Query("content"));

            
            #line default
            #line hidden
WriteLiteral("\" placeholder=\"");


            
            #line 61 "..\..\Pages\ReceivedPage.cshtml"
                                                                                                                         Write(Strings.MessagesPage_Query_MessageBody);

            
            #line default
            #line hidden
WriteLiteral("\"/>\r\n                                <span class=\"input-group-btn\">\r\n            " +
"                        <button class=\"btn btn-info\">");


            
            #line 63 "..\..\Pages\ReceivedPage.cshtml"
                                                            Write(Strings.MessagesPage_Query_Button);

            
            #line default
            #line hidden
WriteLiteral(@"</button>
                                </span>
                            </div>
                        </div>
                    </form>
                </div>
                <div class=""btn-toolbar btn-toolbar-top"">
                    <button class=""js-jobs-list-command btn btn-sm btn-primary""
                            data-url=""");


            
            #line 71 "..\..\Pages\ReceivedPage.cshtml"
                                 Write(Url.To("/received/requeue"));

            
            #line default
            #line hidden
WriteLiteral("\"\r\n                            data-loading-text=\"");


            
            #line 72 "..\..\Pages\ReceivedPage.cshtml"
                                          Write(Strings.Common_Enqueueing);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n                            disabled=\"disabled\">\r\n                        <spa" +
"n class=\"glyphicon glyphicon-repeat\"></span>\r\n                        ");


            
            #line 75 "..\..\Pages\ReceivedPage.cshtml"
                   Write(Strings.Common_ReConsume);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </button>\r\n\r\n                    ");


            
            #line 78 "..\..\Pages\ReceivedPage.cshtml"
               Write(Html.PerPageSelector(pager));

            
            #line default
            #line hidden
WriteLiteral(@"
                </div>

                <div class=""table-responsive"">
                    <table class=""table"">
                        <thead>
                        <tr>
                            <th style=""width: 30px;"">
                                <input type=""checkbox"" class=""js-jobs-list-select-all""/>
                            </th>
                            <th style=""width: 175px"">");


            
            #line 88 "..\..\Pages\ReceivedPage.cshtml"
                                                Write(Strings.Common_Id);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                            <th>");


            
            #line 89 "..\..\Pages\ReceivedPage.cshtml"
                           Write(Strings.Common_Version);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                            <th>");


            
            #line 90 "..\..\Pages\ReceivedPage.cshtml"
                           Write(Strings.MessagesPage_Table_Group);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                            <th>");


            
            #line 91 "..\..\Pages\ReceivedPage.cshtml"
                           Write(Strings.MessagesPage_Table_Name);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                            <th class=\"min-width\">");


            
            #line 92 "..\..\Pages\ReceivedPage.cshtml"
                                             Write(Strings.MessagesPage_Table_Retries);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n");


            
            #line 93 "..\..\Pages\ReceivedPage.cshtml"
                             if (string.Equals(StatusName, "Processing", StringComparison.CurrentCultureIgnoreCase))
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <th>");


            
            #line 95 "..\..\Pages\ReceivedPage.cshtml"
                               Write(Strings.MessagesPage_Table_State);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n");


            
            #line 96 "..\..\Pages\ReceivedPage.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            <th style=\"width: 75px;\" class=\"align-right\">");


            
            #line 97 "..\..\Pages\ReceivedPage.cshtml"
                                                                    Write(Strings.MessagesPage_Table_ExpiresAt);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                        </tr>\r\n                        </thead>\r\n         " +
"               <tbody>\r\n");


            
            #line 101 "..\..\Pages\ReceivedPage.cshtml"
                         foreach (var message in succeededMessages)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <tr class=\"js-jobs-list-row hover\">\r\n                " +
"                <td>\r\n                                    <input type=\"checkbox\"" +
" class=\"js-jobs-list-checkbox\" name=\"messages[]\" value=\"");


            
            #line 105 "..\..\Pages\ReceivedPage.cshtml"
                                                                                                             Write(message.Id);

            
            #line default
            #line hidden
WriteLiteral("\"/>\r\n                                </td>\r\n                                <td c" +
"lass=\"word-break\">\r\n                                    <a href=\"javascript:;\" d" +
"ata-url=\'");


            
            #line 108 "..\..\Pages\ReceivedPage.cshtml"
                                                                 Write(Url.To("/received/message/") + message.Id);

            
            #line default
            #line hidden
WriteLiteral("\' class=\"openModal\">#");


            
            #line 108 "..\..\Pages\ReceivedPage.cshtml"
                                                                                                                                 Write(message.Id);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                                </td>\r\n                                <td>" +
"\r\n                                    ");


            
            #line 111 "..\..\Pages\ReceivedPage.cshtml"
                               Write(message.Version);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n                                <td clas" +
"s=\"word-break\">\r\n                                    ");


            
            #line 114 "..\..\Pages\ReceivedPage.cshtml"
                               Write(message.Group);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n                                <td>\r\n  " +
"                                  ");


            
            #line 117 "..\..\Pages\ReceivedPage.cshtml"
                               Write(message.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n                                <td>\r\n  " +
"                                  ");


            
            #line 120 "..\..\Pages\ReceivedPage.cshtml"
                               Write(message.Retries);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n");


            
            #line 122 "..\..\Pages\ReceivedPage.cshtml"
                                 if (string.Equals(StatusName, "Processing", StringComparison.CurrentCultureIgnoreCase))
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <td>\r\n                                       " +
" ");


            
            #line 125 "..\..\Pages\ReceivedPage.cshtml"
                                   Write(message.StatusName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n");


            
            #line 127 "..\..\Pages\ReceivedPage.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                                <td class=\"align-right\">\r\n");


            
            #line 129 "..\..\Pages\ReceivedPage.cshtml"
                                     if (message.ExpiresAt.HasValue)
                                    {
                                        
            
            #line default
            #line hidden
            
            #line 131 "..\..\Pages\ReceivedPage.cshtml"
                                   Write(Html.RelativeTime(message.ExpiresAt.Value));

            
            #line default
            #line hidden
            
            #line 131 "..\..\Pages\ReceivedPage.cshtml"
                                                                                   
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </td>\r\n\r\n                            </tr>\r\n");


            
            #line 136 "..\..\Pages\ReceivedPage.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        </tbody>\r\n                    </table>\r\n                <" +
"/div>\r\n                ");


            
            #line 140 "..\..\Pages\ReceivedPage.cshtml"
           Write(Html.Paginator(pager));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");


            
            #line 142 "..\..\Pages\ReceivedPage.cshtml"


            
            #line default
            #line hidden
WriteLiteral(@"            <div>
                <div class=""modal fade"" tabindex=""-1"" role=""dialog"">
                    <div class=""modal-dialog"" role=""document"">
                        <div class=""modal-content"">
                            <div class=""modal-header"">
                                <button type=""button"" class=""close"" data-dismiss=""modal"" aria-label=""Close"">
                                    <span aria-hidden=""true"">&times;</span>
                                </button>
                                <h4 class=""modal-title"">Message Content</h4>
                            </div>
                            <div id=""jsonContent"" style=""max-height: 500px; overflow-y: auto;"" class=""modal-body"">
                            </div>
                            <div class=""modal-footer"">
                                <button type=""button"" class=""btn btn-sm btn-primary"" id=""formatBtn"" onclick="""">");


            
            #line 156 "..\..\Pages\ReceivedPage.cshtml"
                                                                                                          Write(Strings.MessagesPage_Modal_Format);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                                <button type=\"button\" class=\"btn btn-s" +
"m btn-primary\" id=\"rawBtn\" onclick=\"\">");


            
            #line 157 "..\..\Pages\ReceivedPage.cshtml"
                                                                                                       Write(Strings.MessagesPage_Modal_Raw);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                                <button type=\"button\" class=\"btn btn-s" +
"m btn-primary\" id=\"expandBtn\" onclick=\"\">");


            
            #line 158 "..\..\Pages\ReceivedPage.cshtml"
                                                                                                          Write(Strings.MessagesPage_Modal_Expand);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                                <button type=\"button\" class=\"btn btn-s" +
"m btn-primary\" id=\"collapseBtn\" onclick=\"\">");


            
            #line 159 "..\..\Pages\ReceivedPage.cshtml"
                                                                                                            Write(Strings.MessagesPage_Model_Collaspse);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                            </div>\r\n                        </div><!--" +
" /.modal-content -->\r\n                    </div><!-- /.modal-dialog -->\r\n       " +
"         </div><!-- /.modal -->\r\n            </div>\r\n");


            
            #line 165 "..\..\Pages\ReceivedPage.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
