#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetCore.CAP.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Pages\SubscriberPage.cshtml"
    using DotNetCore.CAP.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Pages\SubscriberPage.cshtml"
    using DotNetCore.CAP.Dashboard.Resources;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Pages\SubscriberPage.cshtml"
    using DotNetCore.CAP.Internal;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class SubscriberPage : DotNetCore.CAP.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");






            
            #line 6 "..\..\Pages\SubscriberPage.cshtml"
  
    Layout = new LayoutPage(Strings.SubscribersPage_Title);

    var cache = RequestServices.GetService(typeof(MethodMatcherCache)) as MethodMatcherCache;
    var subscribers = cache.GetCandidatesMethodsOfGroupNameGrouped();


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"row\">\r\n    <div class=\"col-md-12\">\r\n        <h1 class=\"page-header\"" +
">");


            
            #line 15 "..\..\Pages\SubscriberPage.cshtml"
                           Write(Strings.SubscribersPage_Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n\r\n");


            
            #line 17 "..\..\Pages\SubscriberPage.cshtml"
         if (subscribers.Count == 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"alert alert-warning\">\r\n                ");


            
            #line 20 "..\..\Pages\SubscriberPage.cshtml"
           Write(Strings.SubscribersPage_NoSubscribers);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");


            
            #line 22 "..\..\Pages\SubscriberPage.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"table-responsive\">\r\n                <table class=\"table s" +
"ubscribe-table\">\r\n                    <thead>\r\n                    <tr>\r\n       " +
"                 <th width=\"20%\">");


            
            #line 29 "..\..\Pages\SubscriberPage.cshtml"
                                   Write(Strings.Common_Group);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                        <th width=\"40%\">\r\n                            ");


            
            #line 31 "..\..\Pages\SubscriberPage.cshtml"
                       Write(Strings.Common_Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </th>\r\n                        <th>");


            
            #line 33 "..\..\Pages\SubscriberPage.cshtml"
                       Write(Strings.Common_Method);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                    </tr>\r\n                    </thead>\r\n                 " +
"   <tbody>\r\n");


            
            #line 37 "..\..\Pages\SubscriberPage.cshtml"
                     foreach (var subscriber in subscribers)
                    {   
                        var i = 0;
                        var rowCount = subscriber.Value.Count;
                        foreach (var column in subscriber.Value)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <tr>\r\n");


            
            #line 44 "..\..\Pages\SubscriberPage.cshtml"
                                 if (i == 0)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <td rowspan=\"");


            
            #line 46 "..\..\Pages\SubscriberPage.cshtml"
                                            Write(rowCount);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 46 "..\..\Pages\SubscriberPage.cshtml"
                                                       Write(subscriber.Key);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");


            
            #line 47 "..\..\Pages\SubscriberPage.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                                <td>");


            
            #line 48 "..\..\Pages\SubscriberPage.cshtml"
                               Write(column.Attribute.Name);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td>\r\n                                    " +
"<span style=\"color: #00bcd4\">");


            
            #line 50 "..\..\Pages\SubscriberPage.cshtml"
                                                            Write(column.ImplTypeInfo.Name);

            
            #line default
            #line hidden
WriteLiteral("</span>：\r\n                                    <div class=\"job-snippet-code\">\r\n   " +
"                                     <code>\r\n                                   " +
"         <pre>");


            
            #line 53 "..\..\Pages\SubscriberPage.cshtml"
                                            Write(Html.MethodEscaped(column.MethodInfo));

            
            #line default
            #line hidden
WriteLiteral("</pre>\r\n                                        </code>\r\n                        " +
"            </div>\r\n                                </td>\r\n                     " +
"       </tr>\r\n");


            
            #line 58 "..\..\Pages\SubscriberPage.cshtml"
                            i++;
                        }
                    }

            
            #line default
            #line hidden
WriteLiteral("                    </tbody>\r\n                </table>\r\n            </div>\r\n");


            
            #line 64 "..\..\Pages\SubscriberPage.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
